version: 2
jobs:
  build:
    working_directory: /data
    docker:
      - image: docker:18.05.0-ce-git
    environment:
      IMG_NAME: cstoku/scheduling-scaler
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /tmp/img-cache.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/img-cache.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=$IMG_NAME -t $IMG_NAME .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /tmp/img-cache.tar $IMG_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/img-cache.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_ID -p $DOCKER_PASS
            docker push $IMG_NAME:latest
          filters:
            branches:
              only: /^master$/
            tags:
              ignore: /.*/
