version: 2
jobs:
  build:
    working_directory: /data
    docker:
      - image: docker:18.05.0-ce-git
    environment:
      IMG_NAME: cstoku/scheduling-scaler
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t $IMG_NAME:$CIRCLE_SHA1 .
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_ID -p $DOCKER_PASS
            docker tag $IMG_NAME:$CIRCLE_SHA1 $IMG_NAME:latest
            docker push $IMG_NAME:latest
          filters:
            branches:
              only: /^master$/
            tags:
              ignore: /.*/
