// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingScaler) DeepCopyInto(out *SchedulingScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingScaler.
func (in *SchedulingScaler) DeepCopy() *SchedulingScaler {
	if in == nil {
		return nil
	}
	out := new(SchedulingScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingScalerList) DeepCopyInto(out *SchedulingScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchedulingScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingScalerList.
func (in *SchedulingScalerList) DeepCopy() *SchedulingScalerList {
	if in == nil {
		return nil
	}
	out := new(SchedulingScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingScalerSchedule) DeepCopyInto(out *SchedulingScalerSchedule) {
	*out = *in
	in.ScheduleTime.DeepCopyInto(&out.ScheduleTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingScalerSchedule.
func (in *SchedulingScalerSchedule) DeepCopy() *SchedulingScalerSchedule {
	if in == nil {
		return nil
	}
	out := new(SchedulingScalerSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingScalerSpec) DeepCopyInto(out *SchedulingScalerSpec) {
	*out = *in
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = make([]SchedulingScalerSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ScaleTargetRef = in.ScaleTargetRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingScalerSpec.
func (in *SchedulingScalerSpec) DeepCopy() *SchedulingScalerSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingScalerStatus) DeepCopyInto(out *SchedulingScalerStatus) {
	*out = *in
	in.LastScaleTime.DeepCopyInto(&out.LastScaleTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingScalerStatus.
func (in *SchedulingScalerStatus) DeepCopy() *SchedulingScalerStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulingScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingTime) DeepCopyInto(out *SchedulingTime) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingTime.
func (in *SchedulingTime) DeepCopy() *SchedulingTime {
	if in == nil {
		return nil
	}
	out := new(SchedulingTime)
	in.DeepCopyInto(out)
	return out
}
