/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "github.com/cstoku/scheduling-scaler/pkg/apis/scsc/v1alpha1"
	scheme "github.com/cstoku/scheduling-scaler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SchedulingScalersGetter has a method to return a SchedulingScalerInterface.
// A group's client should implement this interface.
type SchedulingScalersGetter interface {
	SchedulingScalers(namespace string) SchedulingScalerInterface
}

// SchedulingScalerInterface has methods to work with SchedulingScaler resources.
type SchedulingScalerInterface interface {
	Create(*v1alpha.SchedulingScaler) (*v1alpha.SchedulingScaler, error)
	Update(*v1alpha.SchedulingScaler) (*v1alpha.SchedulingScaler, error)
	UpdateStatus(*v1alpha.SchedulingScaler) (*v1alpha.SchedulingScaler, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha.SchedulingScaler, error)
	List(opts v1.ListOptions) (*v1alpha.SchedulingScalerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SchedulingScaler, err error)
	SchedulingScalerExpansion
}

// schedulingScalers implements SchedulingScalerInterface
type schedulingScalers struct {
	client rest.Interface
	ns     string
}

// newSchedulingScalers returns a SchedulingScalers
func newSchedulingScalers(c *SchedulingV1alphaClient, namespace string) *schedulingScalers {
	return &schedulingScalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the schedulingScaler, and returns the corresponding schedulingScaler object, and an error if there is any.
func (c *schedulingScalers) Get(name string, options v1.GetOptions) (result *v1alpha.SchedulingScaler, err error) {
	result = &v1alpha.SchedulingScaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("schedulingscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SchedulingScalers that match those selectors.
func (c *schedulingScalers) List(opts v1.ListOptions) (result *v1alpha.SchedulingScalerList, err error) {
	result = &v1alpha.SchedulingScalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("schedulingscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested schedulingScalers.
func (c *schedulingScalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("schedulingscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a schedulingScaler and creates it.  Returns the server's representation of the schedulingScaler, and an error, if there is any.
func (c *schedulingScalers) Create(schedulingScaler *v1alpha.SchedulingScaler) (result *v1alpha.SchedulingScaler, err error) {
	result = &v1alpha.SchedulingScaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("schedulingscalers").
		Body(schedulingScaler).
		Do().
		Into(result)
	return
}

// Update takes the representation of a schedulingScaler and updates it. Returns the server's representation of the schedulingScaler, and an error, if there is any.
func (c *schedulingScalers) Update(schedulingScaler *v1alpha.SchedulingScaler) (result *v1alpha.SchedulingScaler, err error) {
	result = &v1alpha.SchedulingScaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("schedulingscalers").
		Name(schedulingScaler.Name).
		Body(schedulingScaler).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *schedulingScalers) UpdateStatus(schedulingScaler *v1alpha.SchedulingScaler) (result *v1alpha.SchedulingScaler, err error) {
	result = &v1alpha.SchedulingScaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("schedulingscalers").
		Name(schedulingScaler.Name).
		SubResource("status").
		Body(schedulingScaler).
		Do().
		Into(result)
	return
}

// Delete takes name of the schedulingScaler and deletes it. Returns an error if one occurs.
func (c *schedulingScalers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("schedulingscalers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *schedulingScalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("schedulingscalers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched schedulingScaler.
func (c *schedulingScalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha.SchedulingScaler, err error) {
	result = &v1alpha.SchedulingScaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("schedulingscalers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
