apiVersion: scaling.k8s.cstoku.me/v1alpha1
kind: SchedulingScaler
metadata:
  name: example-scheduling-scaler
spec:
  location: "Asia/Tokyo"
  schedules:
  - scheduleTime: "12:00"
    replicas: 10
  - scheduleTime: "18:00"
    replicas: 15
  - scheduleTime: "23:00"
    replicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
